### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by thegodone** [Lambard-ML-Team/SMILES-X#1]
I ran your Example notebook code and got the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-99f5ecded1f1> in <module>
----> 1 main.main(data_smiles=data[['smiles1','smiles2']], # SMILES input
      2           data_prop=data[['median']], # Property of interest
      3           data_err=data[['min', 'max']], # Error on the property
      4           data_name=data_name,
      5           data_units=data_units,

/fwd/SMILES-X/SMILESX/main.py in main(data_smiles, data_prop, data_err, data_extra, data_name, data_units, data_label, smiles_concat, outdir, geomopt_mode, bayopt_mode, train_mode, pretrained_data_name, pretrained_augm, model_type, scale_output, embed_bounds, lstm_bounds, tdense_bounds, nonlin_bounds, bs_bounds, lr_bounds, embed_ref, lstm_ref, tdense_ref, dense_depth, bs_ref, lr_ref, k_fold_number, k_fold_index, run_index, n_runs, check_smiles, augmentation, geom_sample_size, bayopt_n_rounds, bayopt_n_epochs, bayopt_n_runs, n_gpus, gpus_list, gpus_debug, patience, n_epochs, batchsize_pergpu, lr_schedule, bs_increase, ignore_first_epochs, lr_min, lr_max, prec, log_verbose, train_verbose)
   1046 
   1047             # Plot prediction vs observation plots per run
-> 1048             visutils.plot_fit(trues=[y_train_clean_unscaled, y_valid_clean_unscaled, y_test_clean_unscaled],
   1049                               preds=[y_pred_train_mean_augm, y_pred_valid_mean_augm, y_pred_test_mean_augm],
   1050                               errs_true=[y_err_train, y_err_valid, y_err_test],

/fwd/SMILES-X/SMILESX/visutils.py in plot_fit(trues, preds, errs_true, errs_pred, err_bars, save_dir, dname, dlabel, units, fold, run, final, model_type)
    302             # (N, ) for symmetric errors, (2, N) for asymmetric errors
    303             if err_bars is not None:
--> 304                 err_true = error_format(true, err_true, err_bars)
    305 
    306             # Legend printing for train/val/test

/fwd/SMILES-X/SMILESX/visutils.py in error_format(val, err, bars)
    442             # Switch from min/max range to the lengths of error bars
    443             # to the left/right from the mean or median value
--> 444             return np.abs(val-err).T
    445         # If three error values are given, they are treated as [std, min, max]
    446         elif err.shape[1]==3:

ValueError: operands could not be broadcast together with shapes (5,) (5,2) 

Do you know how to fix it ?

**Comment by egracheva** [comment]
Hello, thanks for reporting the error. I have reproduced it.
I will get back to you with the solution as soon as possible.

**Comment by egracheva** [comment]
I have fixed the bug for me. 
Could you please pull the most recent version and confirm that it runs for you?

**Comment by egracheva** [comment]
Resolved and closed due to inactivity.
